import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"], style: "normal", weight: ['400', '500'] });

export const metadata: Metadata = {
  title: "Lony - Ladies Of New York",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
